### ISSUE TITLE
How about add onTap event for the breadcrumb item?

### ISSUE THREAD

**Issue by chinshou** [payam-zahedi/flutter_breadcrumb#1]
How about add onTap event for the breadcrumb item?
best regards

**Comment by payam-zahedi** [comment]
Hi @chinshou , we have [onTap](https://github.com/payam-zahedi/flutter_breadcrumb/blob/c6be8bac3daad43096f6a0b0c9446b766a129995/lib/src/breadcrumb_item.dart#L7) property in [BreadCrumbItem ](https://github.com/payam-zahedi/flutter_breadcrumb/blob/master/lib/src/breadcrumb_item.dart)class you can use it to add a callback to your BreadCrumbItem. your code will be something like this: 

```dart
BreadCrumb.builder(
            itemCount: _itemCount,
            builder: (index) {
              return BreadCrumbItem(content: Text('Item $index'), onTap: () {});
            },
            divider: Icon(
              Icons.chevron_right,
              color: Colors.red,
            ),
            overflow: ScrollableOverflow(
              direction: _isHorizontal ? Axis.horizontal : Axis.vertical,
              reverse: _reverse,
              keepLastDivider: _lastDivider,
              controller: _scrollController,
            ),
          ),
```

you can check [example project](https://github.com/payam-zahedi/flutter_breadcrumb/tree/master/example) for more information

**Comment by payam-zahedi** [comment]
I will close this for now. if you have any question please let me know.
