### ISSUE TITLE
Whats about null-safety

### ISSUE THREAD

**Issue by SergeShkurko** [payam-zahedi/flutter_breadcrumb#2]
Flutter v2.0 recommends use null-safety

**Comment by payam-zahedi** [comment]
hi @SergeShkurko, thanks for reminding me. I will work on it and let you know.

**Comment by payam-zahedi** [comment]
@SergeShkurko package fully migrated with null-safety. just upgrade the version of the package to v1.0.0 and use it.
thanks for opening this issue. I will close this issue for now but you can check the package and open it again if needed.
