### ISSUE TITLE
Default hardcoded colors do not fit in dark theme

### ISSUE THREAD

**Issue by alexeyinkin** [payam-zahedi/flutter_breadcrumb#3]
A recent version introduced these hardcoded defaults in `BreadCrumbItem`:
```
    this.textColor = Colors.black,
    this.disabledTextColor = Colors.black54,
```
With dark theme it means black text on near-black background which is no how it should be. The last version I was using before upgrading was `0.1.2` and it did not have this issue, the text was white.

I know it is easy to pass my colors there but looking nice out of the box is better. Please use theme defaults again.

**Comment by payam-zahedi** [comment]
Hi @alexeyinkin  thanks for this Issue, I will fix this ASAP.

**Comment by payam-zahedi** [comment]
@alexeyinkin I resolve this issue. you can use the [1.0.1 version](https://pub.dev/packages/flutter_breadcrumb).
